query GetPage($slug: String = "") {
  pageCollection(where: { slug: $slug }, limit: 1) {
    items {
      pageTitle
      slug
      sys {
        id
      }
      sectionsCollection {
        items {
          __typename
          ... on SectionHero {
            sys {
              id
            }
            title
            subtitle
            backgroundImage {
              title
              url
            }
          }
          ... on SectionCarousel {
            sys {
              id
            }
            title
            carouselImagesCollection {
              items {
                sys {
                  id
                }
                title
                description
                url
              }
            }
          }
        }
      }
    }
  }
}
