query GetPage($slug: String = "") {
  pageCollection(where: { slug: $slug }, limit: 1) {
    items {
      pageTitle
      slug
      sys {
        id
      }
      sectionsCollection {
        items {
          __typename
          title
          subtitle
          backgroundImage {
            title
            url
          }
        }
      }
    }
  }
}
