import ContactForm from '@/components/ContactForm';
import { Container, Heading, VStack, Text } from '@chakra-ui/react';
import Head from 'next/head';

const Contact = () => {
  return (
    <>
      <Head>
        <title>Arely Gizel Photography</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container textAlign='center' p={4}>
        <VStack gap={8}>
          <Heading>{`Let's Start Your Journey`}</Heading>
          <Text>Fill out information below and I{`'`}ll be in touch soon!</Text>
        </VStack>
      </Container>
      <ContactForm />
    </>
  );
};

export default Contact;
