import PageSections from '@/components/PageSections';
import { GetPageQuery } from '@/graphql/contentful/generated/types';
import getPageData from '@/queries/get-page-data';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

interface Props {
  pageContent: NonNullable<
    NonNullable<GetPageQuery['pageCollection']>['items'][0]
  >;
}

const Page = ({ pageContent }: Props) => {
  return (
    <>
      <Head>
        <title>Arely Gizel Photography</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageSections sectionsCollection={pageContent.sectionsCollection} />
    </>
  );
};

export default Page;

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  try {
    const slug = params?.slug;
    if (typeof slug !== 'string') throw new Error();

    const { pageContent } = await getPageData(slug);

    return {
      props: {
        pageContent
      }
    };
  } catch (error) {
    return {
      notFound: true
    };
  }
};
