import { GetPageAboutMeQuery } from '@/graphql/contentful/generated/types';
import getAboutMeData from '@/queries/get-aboutme-data';
import { Box, Flex, Heading, Image, Text } from '@chakra-ui/react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

interface Props {
  aboutMeContent: NonNullable<
    NonNullable<GetPageAboutMeQuery['aboutMeCollection']>['items'][0]
  >;
}

const about = ({ aboutMeContent }: Props) => {
  const { title, description, featuredImage, myPhotosCollection } =
    aboutMeContent;
  return (
    <>
      <Head>
        <title>Arely Gizel Photography</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Flex w='full' flexDir='column' gap={4}>
        <Flex
          p={16}
          gap={8}
          flexDirection={['column', 'column', 'row']}
          w='full'
          alignContent='center'
          justifyContent='center'
        >
          <Image
            src={featuredImage?.url ?? ''}
            alt={featuredImage?.__typename}
            w={['full', 'full', 'md']}
          />
          <Flex direction={'column'} justifyContent='center' gap={4}>
            <Heading as='h2' size='lg' fontWeight='normal'>
              {title}
            </Heading>
            <Text size='md'>{description}</Text>
          </Flex>
        </Flex>
        <Flex
          p={4}
          wrap='wrap'
          justifyContent='center'
          m='auto'
          gap={4}
          mt={10}
          h='full'
          w='full'
        >
          {!myPhotosCollection ? (
            <></>
          ) : (
            myPhotosCollection.items.map((photo, idx) => (
              <Box
                key={`${photo?.url}${idx}`}
                height='280px'
                flex='1 1 auto'
                position='relative'
              >
                <Image
                  src={photo?.url ?? ''}
                  alt={photo?.description ?? ''}
                  objectFit='cover'
                  h='full'
                  w='full'
                  verticalAlign='middle'
                />
              </Box>
            ))
          )}
        </Flex>
      </Flex>
    </>
  );
};

export default about;

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const { aboutMeContent } = await getAboutMeData();

    if (!aboutMeContent) throw new Error();

    return {
      props: {
        aboutMeContent
      }
    };
  } catch {
    return {
      notFound: true
    };
  }
};
